# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build zero-one-group`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t zero-one-group`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system zero-one-group && \
          adduser --system -G zero-one-group zero-one-group

COPY dist/zero-one-group zero-one-group
RUN chown -R zero-one-group:zero-one-group .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix zero-one-group --omit=dev -f install

CMD [ "node", "zero-one-group" ]
